name: QA Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  cypress:
    name: Cypress UI + API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cypress tests
        uses: cypress-io/github-action@v7
        with:
          browser: chrome
          spec: cypress/e2e/**/*.cy.ts

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore


  performance:
    name: k6 Performance Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 performance test
        uses: grafana/run-k6-action@v1
        with:
          path: performance/api-load-test.js


  percy:
    name: Percy Visual Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Percy visual tests
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npx percy exec -- npx cypress run --spec "cypress/e2e/visual.cy.ts" --browser chrome